version: 2.1

orbs:
  cloudrun: circleci/gcp-cloud-run@1.0

jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: "gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}"
          source: ./sample
      - cloudrun/deploy:
          platform: managed
          image: "gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}"
          service-name: "example-service"
          region: "us-east1"
          unauthenticated: true

workflows:
  deploy_service:
    jobs:
      - build_and_deploy